=== kevinqiu1990/TCNN/data/projects/forrest-0.8/main/webapp/resources/schema/dtd/tab-cocoon-v11.dtd
<!--
  Licensed to the Apache Software Foundation (ASF) under one or more
  contributor license agreements.  See the NOTICE file distributed with
  this work for additional information regarding copyright ownership.
  The ASF licenses this file to You under the Apache License, Version 2.0
  (the "License"); you may not use this file except in compliance with
  the License.  You may obtain a copy of the License at

      http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.
-->
<!-- ===================================================================
     
     Apache Cocoon Documentation Tab DTD (Version 1.0)

PURPOSE:
This DTD defines the */tab.xml documentation configuration files.  Tabs are
visual indicators that a certain subsection of the URI space is being browsed.

TYPICAL INVOCATION:

  <!DOCTYPE tab PUBLIC
       "-//APACHE//DTD Cocoon Documentation Tab Vx.yz//EN"
       "tab-cocoon-vxyz.dtd">

  where 
  
    x := major version
    y := minor version
    z := status identifier (optional)
      
NOTES:
  
FIXME:
  - find the proper DTD for top.xml

CHANGE HISTORY:
  20020506 Initial version. (BVK)
  20021102 Revised to allow either @dir or @href (JT)
  20030521 Add @id (JT)
  20031223 Allow nested tags (RDG)
    
==================================================================== -->
<!ELEMENT tabs (tab)*>
<!ELEMENT tab (tab)*>
<!ATTLIST tabs
  software CDATA #REQUIRED
  title CDATA #REQUIRED
  copyright CDATA #REQUIRED
  xmlns:xlink CDATA #IMPLIED
>
<!ATTLIST tab
  id CDATA #IMPLIED
  label CDATA #REQUIRED
  dir CDATA #IMPLIED
  indexfile CDATA #IMPLIED
  href CDATA #IMPLIED
  type (visible | hidden) "visible"
>
<!-- =============================================================== -->
<!-- End of DTD -->
<!-- =============================================================== -->

=== kevinqiu1990/TCNN/data/projects/forrest-0.8/site-author/content/xdocs/tabs.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
  Licensed to the Apache Software Foundation (ASF) under one or more
  contributor license agreements.  See the NOTICE file distributed with
  this work for additional information regarding copyright ownership.
  The ASF licenses this file to You under the Apache License, Version 2.0
  (the "License"); you may not use this file except in compliance with
  the License.  You may obtain a copy of the License at

      http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.
-->
<!DOCTYPE tabs PUBLIC "-//APACHE//DTD Cocoon Documentation Tab V1.1//EN" "http://forrest.apache.org/dtd/tab-cocoon-v11.dtd">
<tabs software="Forrest"
    title="Apache Forrest"
    copyright="2007 The Apache Software Foundation"
    xmlns:xlink="http://www.w3.org/1999/xlink">
<!-- The rules for tabs are:
    @dir will always have '/@indexfile' added.
    @indexfile gets appended to @dir if the tab is selected. Defaults to 'index.html'
    @href is not modified unless it is root-relative and obviously specifies a
    directory (ends in '/'), in which case /index.html will be added
    If @id's are present, site.xml entries with a matching @tab will be in that tab.

   Tabs can be embedded to a depth of two. The second level of tabs will only 
    be displayed when their parent tab is selected.    
  -->
  <tab id="home" label="Welcome" dir=""/>
  <tab id="project" label="Developers" dir="" indexfile="contrib.html"/>
  <tab id="docs" label="Versioned Docs" dir="versions">
    <tab id="v0_80" label="0.80 (current)" dir="docs_0_80"/>
    <tab id="v0_90" label="0.90-dev (under development)" dir="docs_0_90"/>
    <tab id="v0_70" label="0.70 (past)" dir="docs_0_70"/>
  </tab>
  <tab id="plugins" label="Plugins" dir="pluginDocs">
    <tab id="p0_80" label="0.80 (current)" dir="pluginDocs/plugins_0_80"/>
    <tab id="p0_90" label="0.90-dev (under development)" dir="pluginDocs/plugins_0_90"/>
    <tab id="p0_70" label="0.70 (past)" dir="pluginDocs/plugins_0_70"/>
  </tab>
  <tab id="tools" label="Tools" dir="tools"/>
</tabs>
